### ISSUE TITLE
xcowsay crashes with exit status 139

### ISSUE THREAD

**Issue by samueloph** [nickg/xcowsay#4]
Hello, we've received the following bug report on Debian and i would like to make you aware of that.

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=716495

The attachment[1] from the bugreport allows reproducibility* of the problem and i confirmed it affects v1.3. 

It doesn't look like a big deal though, but i may be wrong.

*There's a script under ./crash that segfaults xcowsay.

[1]https://bugs.debian.org/cgi-bin/bugreport.cgi?att=1;bug=716495;filename=xcowsay-report.tar.bz2;msg=5

**Comment by nickg** [comment]
This was actually fixed on the git master branch a few years ago with this commit 81f2505a2cc. I just released a 1.4 version which you can get from the link below that has this fix and a couple of other minor improvements.

http://www.nickg.me.uk/files/xcowsay-1.4.tar.gz

**Comment by samueloph** [comment]
Wow, thanks a lot @nickg, i'm preparing the Debian packaging right now.

**Comment by samueloph** [comment]
@nickg I think you left some .gmo files on some tarballs.

These ones have gmo files:
https://github.com/nickg/xcowsay/releases/download/v1.4/xcowsay-1.4.tar.gz
http://www.nickg.me.uk/files/xcowsay-1.4.tar.gz

And these ones don't:
https://github.com/nickg/xcowsay/archive/v1.4.zip
https://github.com/nickg/xcowsay/archive/v1.4.tar.gz

I believe you'd want to make a tarball withou any po/*.gmo files.

Is that right? Can you fix that please?

Thanks a lot.

**Comment by nickg** [comment]
@samueloph I think including the compiled .gmo files is correct: the `xcowsay-1.4.tar.gz` is generated by autotools' `make dist` (same as previous releases). The "Source code" zips github generates are just snapshots of the git tree, which don't have those.

**Comment by samueloph** [comment]
Thanks for the explanation, the new release should arrive to Debian Unstable this week.
