### ISSUE TITLE
GTK 3 compatibility

### ISSUE THREAD

**Issue by dasJ** [nickg/xcowsay#6]
See my [nixpkgs PR](https://github.com/NixOS/nixpkgs/pull/79024#issuecomment-581068533).

GDK seems to be deprecated years ago and for packaging in modern distros, more modern dependencies would be awesome

**Comment by nickg** [comment]
I started porting it to Cairo ages ago but never finished. I'll try to that done soon.

**Comment by nickg** [comment]
I just pushed a bunch of commits to update to Gtk3/Cairo. A downside of upgrading is that the API we used for transparency has been removed, which means we have to use the alpha channel and that requires a compositing window manager.

The new tar file is here: http://www.nickg.me.uk/files/xcowsay-1.5.tar.gz

Can you try it and see if this works for you?

**Comment by dasJ** [comment]
Nice it seems to work! Thanks a lot for the quick response :)
