### ISSUE TITLE
Add fractional time support

### ISSUE THREAD

**Issue by sanjarcode** [nickg/xcowsay#8]
I use xcowsay as a very simple debug tool for GUI apps, because xcowsay is portable(I won't have to write a Gnome or Unity script ) and pops up even inside running games etc. The only problem is that it's too long. Can you allow for fractional times?
If it is possible, tell me, I'll try to submit a PR.

**Comment by nickg** [comment]
It's possible to do it at the moment with the config file. E.g. if you put the following in `~/.config/xcowsayrc` to display for 0.5s:

```
min_display_time = 500
display_time = 500
```
I guess the `-t` option could be extended to allow a floating point value like `-t 0.5` too.

**Comment by nickg** [comment]
I added support for fractional times in the -t argument like `-t 0.5` and the config file allows you to to specify time time in milliseconds. Let me know if you need something more.
